### ISSUE TITLE
Strip types not working?

### ISSUE THREAD

**Issue by orta** [lorefnon/vite-plugin-civet#2]
Hey there, cool work!

I spotted that when I had code like:

```tsx
export const getInitialCode = (fallback: string, location: Location) => {} 
```

It would be converted into:

```jsx
export const getInitialCode = (fallback: string, location: Location) => {}
```

Which was used inside a .jsx file - causing a type error.

The settings were the default in the React example, using v0.2.1:

```
  civetPlugin({
      stripTypes: true,
      outputExtension: 'jsx',
      outputTransformerPlugin: 'vite:react-swc',
    }),
```

( I fixed by switching the output to tsx)

**Comment by edemaine** [comment]
`stripTypes` should be working now, in v0.2.3.  Let us know if you run into this issue again!
