### ISSUE TITLE
support for decorators

### ISSUE THREAD

**Issue by kwaa** [lorefnon/vite-plugin-civet#8]
Libraries like `lit` only use the TypeScript decorators, and there doesn't seem to be a proper way to use with `vite-plugin-civet`. (unless the component is written in js style)

I have tried `@rollup/plugin-typescript`, `@vitejs/plugin-react-swc`, `vite-plugin-babel`, `vite-plugin-solid`, all of them have more or less problems making it unusable.

**Comment by edemaine** [comment]
Just checking: Did you try including the plugin in the `outputTransformerPlugin` option, and setting `stripTypes: false` and `outputExtension: 'tsx'`, as in the examples such as [this one](https://github.com/lorefnon/vite-plugin-civet/blob/main/playground-solid/vite.config.ts)?

**Comment by kwaa** [comment]
> Just checking: Did you try including the plugin in the `outputTransformerPlugin` option, and setting `stripTypes: false` and `outputExtension: 'tsx'`, as in the examples such as [this one](https://github.com/lorefnon/vite-plugin-civet/blob/main/playground-solid/vite.config.ts)?

I did, and neither solid nor react-swc worked properly.

solid gives similar results to `vite-plugin-babel`, prompting me to install the plugin.

```bash
/a2z/z/src/components/nav.civet.tsx: Support for the experimental syntax 'decorators' isn't currently enabled (18:1):

  16 |  *   - @see {@link https://github.com/material-components/material-web/issues/441}
  17 |  */
> 18 | @customElement('a2z-nav')
     | ^
  19 | class Nav extends LitElement {
  20 |   render() {
  21 |     return html`

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.
```

And when I installed the plug-in after the terminal no longer reported an error, but the page can not be displayed properly.

```ts
  plugins: [
    solidPlugin({
      babel: {
        plugins: [
          ['@babel/plugin-proposal-decorators', { version: 'legacy' }],
          ['@babel/plugin-proposal-class-properties'],
        ],
      },
    }),
    civetPlugin({
      stripTypes: false,
      outputExtension: 'tsx',
      outputTransformerPlugin: 'solid',
    }),
    template(),
    tsconfigPaths(),
  ],
```

```
// reactive-element.ts:1304 console.error
Uncaught (in promise) Error: The following properties on element a2z-nav will not trigger updates as expected because they are set using class fields: router. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
    at Nav.performUpdate (reactive-element.ts:1304:17)
    at Nav.scheduleUpdate (reactive-element.ts:1263:17)
    at Nav.__enqueueUpdate (reactive-element.ts:1235:25)
```

react-swc, on the other hand, gives me an error about app.ts, which may be related to the fact that my code itself doesn't use React.

```bash
2:24:55 PM [vite] Internal server error: 
  × Expression expected
    ╭─[/a2z/z/src/app.ts:22:1]
 22 │     message: 'Hello, World!',
 23 │   })
 24 │ 
 25 │ @customElement('a2z-app')
    · ─
 26 │ export class App extends LitElement {
 27 │   render() {
 27 │     return html`
    ╰────


Caused by:
    Syntax Error
  Plugin: vite:react-swc
  File: /a2z/z/src/app.ts:22:1
```

**Comment by lorefnon** [comment]
I have added an [example](https://github.com/lorefnon/vite-plugin-civet/tree/main/playground-lit) which uses babel to transpile decorators. Let us know if this works for you.

**Comment by kwaa** [comment]
> I have added an [example](https://github.com/lorefnon/vite-plugin-civet/tree/main/playground-lit) which uses babel to transpile decorators. Let us know if this works for you.

Available! There are still some minor issues with relative path imports and such though.

I will close this issue... also, pls update the `@danielx/civet` version.
